name: CI/CD
permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use latest version of bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

         # 1) intall dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile

         # 2) Lint check
      - name: Lint check
        run: bun lint

        # 3) test check
      - name: Run tests
        run: bun test-report

        # 4) Coverage upload
      - name: Upload coverage to comment
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: './coverage/coverage-summary.json'
          json-final-path: './coverage/coverage-final.json'

        # 5) Build app
      - name: Build
        run: bun run build