name: CI/CD
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    # Inputs the workflow accepts.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Use bun 1.0.11
          run: echo "Hello World"
